apiVersion: v1
kind: Service
metadata:
  name: pgvector
  namespace: fraud-detect
spec:
  selector:
    app: pgvector
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # Headless pour StatefulSet
